name: GitHub Actions Demo
on: [push]
jobs:
    docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:       
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: joe991/todo-list:latest
      - run: echo done