name: GitHub Actions Demo
on: [push]
jobs:
    docker-build:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERUSER }}
            password: ${{ secrets.DOCKERTOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: joe991/todo-list:latest
        - run: echo done


    docker-deploy:
      needs: docker-build
      runs-on: [dev]
      steps:
        - name: running a docker container
          run: sudo docker run -dp 127.0.0.1:3000:3000 joe991/todo-list:latest

        - name: check the running container
          run: sudo docker ps